### ISSUE TITLE
"Not able to process more than 1 channels"

### ISSUE THREAD

**Issue by a-stew** [anfractuosity/musicplayer#1]
The error "Not able to process more than 1 channels" appears when attempting to play a file converted with the SoX method stated.

**Comment by anfractuosity** [comment]
Hi, sorry about the delay, only just noticed this issue somehow.

The issue is, the program I created needs a mono file.  I believe the following 
command should work for you:

```
sox in.wav out.wav channels 1 rate 1000000
```

Hope that helps!
